#!/bin/bash
if [ $# -lt 1 ]; then
    echo -e "Usage: jgrep [keyword] to search keyword in current git repo's Java & Kotlin files"
else
    git grep --recurse-submodules -ni "$1" -- '*.cpp' '*.c' '*.h' '*.hpp'

    #git submodule foreach "git grep -ni \"$1\"  -- '*.java'; true"
fi
